# Generated by Django 5.2.9 on 2025-12-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
