# Generated by Django 5.2.9 on 2025-12-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_datospersonales_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
