# Generated by Django 5.2.9 on 2025-12-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_datospersonales_email_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='archivocv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
