# Generated by Django 5.2.9 on 2025-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_datospersonales_archivocv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
    ]
