# Generated by Django 5.2.9 on 2025-12-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0005_alter_reconocimientos_descripcionreconocimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosrealizados',
            name='archivo_extra',
            field=models.FileField(blank=True, null=True, upload_to='extras_reconocimientos/'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='archivo_recurso',
            field=models.FileField(blank=True, null=True, upload_to='recursos_cursos/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=100),
        ),
    ]
