# Generated by Django 5.2.9 on 2025-12-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0006_cursosrealizados_archivo_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='documento_interes',
            field=models.FileField(blank=True, null=True, upload_to='garage/documentos/', verbose_name='Documento Adicional (PDF/Foto)'),
        ),
    ]
