# Generated by Django 5.2.9 on 2026-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0007_ventagarage_documento_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecurso',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
