# Generated by Django 5.2.9 on 2026-01-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0008_alter_cursosrealizados_descripcioncurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='archivo_extra',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='archivo_recurso',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='archivo_cursos_completo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/consolidado/'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='archivo_reconocimientos_completo',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/consolidado/'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
