# Generated by Django 5.2.9 on 2026-01-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0009_remove_cursosrealizados_archivo_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoslaborales',
            name='url_proyecto',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace al Proyecto (Opcional)'),
        ),
    ]
