# Generated by Django 5.2.9 on 2026-01-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0010_productoslaborales_url_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='archivo_cursos_completo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='archivocv',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='archivo_reconocimientos_completo',
        ),
    ]
