# Generated by Django 5.2.9 on 2026-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0011_remove_datospersonales_archivo_cursos_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
