# Generated by Django 5.2.9 on 2026-01-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0012_alter_datospersonales_numerocedula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={},
        ),
    ]
