# Generated by Django 5.2.9 on 2026-01-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0013_alter_experiencialaboral_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fechainiciogestion']},
        ),
    ]
