# Generated by Django 5.2.9 on 2026-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0014_alter_experiencialaboral_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/fotos/', verbose_name='Foto para la Web'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='documento_interes',
            field=models.FileField(blank=True, null=True, upload_to='garage/documentos/', verbose_name='PDF solo para el CV'),
        ),
    ]
