# Generated by Django 5.2.9 on 2026-01-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0016_remove_ventagarage_documento_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='documento_interes',
            field=models.FileField(blank=True, null=True, upload_to='garage/documentos/', verbose_name='PDF solo para el CV'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='garage/fotos/', verbose_name='Foto para la Web'),
        ),
    ]
